server:
  port: 0
  
eureka:  instance:    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:    service-url:
      default-zone: http://localhost:8761/

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000
      